/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja;

import dao.ProdutoDAO;
import java.util.List;
import modelo.Produto;

/**
 *
 * @author Vanessa Ortiz
 */
public class LojaTela extends javax.swing.JFrame {
List<Produto> lista;
ProdutoDAO dao ;
Integer posicao;

    public LojaTela() {
        initComponents();
        
        dao = new ProdutoDAO();
        posicao = 0;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        txtPB = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JLabel();
        txtPB1 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JLabel();
        txtPreco2 = new javax.swing.JLabel();
        txtPB2 = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Preço");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Preço Bombástico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Preço Bombástico");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Preço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Nome");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Preço Bombástico");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Preço");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Nome");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CONFIRA NOSSOS PRINCIPAIS DESTAQUES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1280, 160));

        jButton1.setBackground(new java.awt.Color(25, 25, 25));
        jButton1.setFont(new java.awt.Font("Maiandra GD", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("LOJAS RECOMENDADAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, -1, -1));

        txtNome.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 220, 20));

        txtPreco.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtPreco.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 210, 20));

        txtPB.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtPB.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 130, 20));

        txtNome1.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtNome1.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 220, 20));

        txtPreco1.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtPreco1.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 210, 20));

        txtPB1.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtPB1.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtPB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 130, 20));

        txtNome2.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtNome2.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 220, 20));

        txtPreco2.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtPreco2.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtPreco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 210, 20));

        txtPB2.setFont(new java.awt.Font("Maiandra GD", 3, 14)); // NOI18N
        txtPB2.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtPB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 130, 20));

        lblTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arquivo_imagem/FunoProd.png"))); // NOI18N
        lblTema.setText("                ");
        getContentPane().add(lblTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LojasRecomendadas tela = new LojasRecomendadas();

                tela.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        List<Produto> lista = dao.select();
        
           
            
            
            

            Produto info = lista.get(0);
            
            txtNome.setText(info.getP_name());
            txtPreco.setText(info.getP_price().toString());
            txtPB.setText(info.getP_blackprice().toString());
            
            Produto info1 = lista.get(1);
            
            txtNome1.setText(info1.getP_name());
            txtPreco1.setText(info1.getP_price().toString());
            txtPB1.setText(info1.getP_blackprice().toString());
            
            Produto info2 = lista.get(2);
            
            txtNome2.setText(info2.getP_name());
            txtPreco2.setText(info2.getP_price().toString());
            txtPB2.setText(info2.getP_blackprice().toString());
            
             
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LojaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNome1;
    private javax.swing.JLabel txtNome2;
    private javax.swing.JLabel txtPB;
    private javax.swing.JLabel txtPB1;
    private javax.swing.JLabel txtPB2;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtPreco1;
    private javax.swing.JLabel txtPreco2;
    // End of variables declaration//GEN-END:variables
}
